spring:

  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 5


  datasource:
    url: jdbc:mysql://127.0.0.1:3306/Memilog?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: fpalffldk8923@
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connectionTimeout: 60000
      maximumPoolSize: 5

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true